Repository milieuinfo/webcomponent-vl-ui-form-message, pull requests merged in 2019-09, with the labels that each got.

#17 UIG-218
  vl-form-message.src.js
Labels: maintenance

#18 Update link naar demo
  vl-form-message.src.js
Labels: maintenance

#19 Update link naar demo
  vl-form-message.src.js
Labels: maintenance

#20 Automatic commit via update script
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/task.md
  package-lock.json
  package.json
Labels: maintenance

#23 Update dependency vl-ui-core to v1.4.6
  package-lock.json
  package.json
Labels: dependencies

#22 Update dependency replace to v1.1.1
  package-lock.json
  package.json
Labels: dependencies

#21 Update dependency @govflanders/vl-ui-form-message to v3.9.0
  package-lock.json
  package.json
Labels: dependencies

#8 Update dependency np to v3.1.0
  package-lock.json
  package.json
Labels: dependencies, renovate

#27 UIG-143 - Update bamboo template
  demo/demo.css
  package-lock.json
  package.json
  style.css
Labels: maintenance

#28 Update vl-ui-util
  CODEOWNERS
  demo/demo.css
  package-lock.json
  package.json
  style.css
Labels: maintenance
