Repository milieuinfo/webcomponent-vl-ui-form-message, pull requests merged in 2020-01, with the labels that each got.

#40 Update vl-ui-util
  bamboo-specs/bamboo.yml
  demo/demo.css
  demo/demo.js
  package-lock.json
  package.json
  test/docker-compose.yml
Labels: maintenance

#41 Update naar laatste util
  package-lock.json
  package.json
Labels: bugfix

#42 Classname en export waren verkeerd + upgrade naar laatste core
  package-lock.json
  package.json
  test/e2e/pages/vl-form-message.page.js
Labels: bugfix

#45 Verwijder pretest fase (installeren chromedriver). Deze komt via vl-ui-util binnenDepend op core-branch zonder after
  package.json
Labels: chore

#43 Overbodig NPM release import scripts verwijderd
  package.json
Labels: maintenance

#44 Update vl-ui-util
  demo/demo.css
  package-lock.json
  package.json
  style.css
  test/docker-compose.yml
Labels: maintenance

#46 Update vl-ui-util
  bamboo-specs/bamboo.yml
  package-lock.json
  package.json
  test/docker-compose.yml
Labels: maintenance

#47 Update vl-ui-util
  bamboo-specs/bamboo.yml
  docker-compose-release.yml
  package-lock.json
  package.json
Labels: maintenance
